# Generated by Django 5.2.5 on 2025-09-30 01:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_fit_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fit',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
