# Generated by Django 5.2.5 on 2025-09-30 02:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_fit_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fit',
            new_name='Product',
        ),
    ]
